/**
 * Compile the per-team JSONs under BSRData/Teams/<group>/<team-slug>.json into
 * the manifest the web app fetches first (BSRData/Teams/Index.json).
 *
 * Layout — one file per comp, foldered by the CONTENT the comp is for:
 *
 *   BSRData/Teams/general/ts-mono.json         <- Co-op / Guild Boss / Events
 *   BSRData/Teams/frenzy-feast/kenny-f2p.json  <- Frenzy Feast
 *   BSRData/Teams/story/f2p-starter.json       <- Story Mode
 *   BSRData/Teams/Index.json                   <- GENERATED (this file)
 *
 * Why group by content rather than tier or rank: content is how a player
 * actually reaches for a comp ("what am I running today?"), and it survives
 * balance patches — tier and rank churn every time the meta moves, which would
 * mean renaming files (and breaking any bookmarked URL) for a reason that has
 * nothing to do with identity. Tier/rank stay as FIELDS, where they belong.
 *
 * Unlike banners, the manifest carries the full member list: the Team Builder,
 * Battle Simulator and every character page filter across ALL comps at once, so
 * a summary that omitted members would just force every file to load anyway.
 * The heavy part — rotations, per-step icons, notes — stays in the per-team
 * file and loads only when a comp is opened.
 *
 * Adding a comp: drop a new JSON in the right group folder and re-run.
 *
 * Run:  node BSRData/GenerateTeamIndex.mjs
 * Wired into Build.ps1 (step 2e).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(here, 'Teams');
const OUT_FILE = path.join(DIR, 'Index.json');

/** Kept in lockstep with Web/Source/Lib/Data.ts `safeSegment` — see the note in
 * GenerateBannerIndex.mjs for why this is validated on both sides. */
const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Rotation goals — the "What would you like to optimize for?" buttons the Team
 * Builder shows above a comp's rotation, one per kind of content a comp gets
 * run for. Kept in lockstep with `RotationGoalId` and GOAL_CATALOG in
 * Web/Source/Lib/RotationGoals.ts, and ordered the same way there.
 *
 * "coop-boss" is the ONLY nested goal: it renders as a button that opens a
 * second row of per-boss options, so those rotations must also carry a `boss`
 * id. Validated here rather than left to the client because a typo'd goal would
 * otherwise show up as a silently missing button — the kind of thing nobody
 * notices until someone asks where their rotation went.
 */
const GOAL_IDS = new Set(['general', 'coop-boss', 'events', 'frenzy-feast']);
const ROTATION_KEYS = ['p2w-rotations', 'f2p-rotations', 'rotations'];

/** Validates every rotation's goal/boss and returns the distinct goal ids the
 *  comp offers, so the listing can badge a comp without loading its rotations. */
function collectGoals(team, rel) {
  const found = new Set();
  for (const key of ROTATION_KEYS) {
    const list = team[key];
    if (list === undefined) continue;
    if (!Array.isArray(list)) throw new Error(`Teams: ${rel} — "${key}" must be an array.`);
    for (const r of list) {
      // Untagged rotations are the legacy shape and mean "general".
      const goal = r.goal ?? 'general';
      if (!GOAL_IDS.has(goal)) {
        throw new Error(
          `Teams: ${rel} — rotation "${r.name}" has unknown goal "${r.goal}". ` +
            `Known goals: ${[...GOAL_IDS].join(', ')}.`,
        );
      }
      if (goal === 'coop-boss') {
        if (!r.boss || !SLUG_RE.test(r.boss)) {
          throw new Error(
            `Teams: ${rel} — rotation "${r.name}" is goal "coop-boss", so it needs a kebab-case ` +
              `"boss" id (it is the one nested goal, and the boss id is which button reaches it).`,
          );
        }
      } else if (r.boss) {
        throw new Error(
          `Teams: ${rel} — rotation "${r.name}" has a "boss" but goal "${goal}". ` +
            `Only "coop-boss" rotations nest under a boss.`,
        );
      }
      found.add(goal);
    }
  }
  return [...GOAL_IDS].filter((g) => found.has(g));
}

const NOTE =
  'GENERATED by BSRData/GenerateTeamIndex.mjs from BSRData/Teams/<group>/*.json — edit the ' +
  'per-team files there, never this one. Entries carry the roster + ranking fields; rotations ' +
  'and step-by-step notes live in the per-team file at `path`. `goals` lists which optimisation ' +
  'goals the comp has rotations for (the Team Builder\'s "What would you like to optimize for?" ' +
  'buttons) — "coop-boss" is the nested one, whose per-boss options come from the rotations\' ' +
  '`boss` ids in the per-team file.';

const groups = fs
  .readdirSync(DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const teams = [];
for (const group of groups) {
  if (!SLUG_RE.test(group)) {
    throw new Error(`Teams: group folder "${group}" must be kebab-case [a-z0-9-].`);
  }

  const files = fs
    .readdirSync(path.join(DIR, group))
    .filter((f) => f.endsWith('.json'))
    .sort();

  for (const file of files) {
    const id = path.basename(file, '.json');
    if (!SLUG_RE.test(id)) {
      throw new Error(`Teams: "${group}/${file}" — filename must be kebab-case [a-z0-9-].`);
    }

    const rel = `${group}/${file}`;
    const team = JSON.parse(fs.readFileSync(path.join(DIR, group, file), 'utf8'));

    if (team.id !== id) {
      throw new Error(`Teams: ${rel} has id "${team.id}" — it must match the filename.`);
    }
    if (team.group !== group) {
      throw new Error(`Teams: ${rel} has group "${team.group}" — it must match the folder.`);
    }
    if (!team.name || !team.name.trim()) throw new Error(`Teams: ${rel} has no name.`);
    if (!Array.isArray(team.members) || team.members.length === 0) {
      throw new Error(`Teams: ${rel} has no members.`);
    }
    for (const m of team.members) {
      if (!m.slug || !SLUG_RE.test(m.slug)) {
        throw new Error(`Teams: ${rel} has a member with a bad slug ("${m.slug}").`);
      }
    }

    const goals = collectGoals(team, rel);

    teams.push({
      id,
      group,
      path: rel,
      name: team.name,
      ...(team.rank !== undefined ? { rank: team.rank } : {}),
      ...(team.tier !== undefined ? { tier: team.tier } : {}),
      ...(team.difficulty !== undefined ? { difficulty: team.difficulty } : {}),
      ...(team.content !== undefined ? { content: team.content } : {}),
      // Which optimisation goals this comp has rotations for. Summary only —
      // the rotations themselves stay in the per-team file.
      ...(goals.length ? { goals } : {}),
      // Members are summarised down to what the cross-comp filters need; the
      // per-member rotation notes stay in the per-team file.
      members: team.members.map((m) => ({
        slug: m.slug,
        name: m.name,
        role: m.role,
        damageType: m.damageType,
        ...(m.swappable?.length ? { swappable: m.swappable } : {}),
      })),
      // Video presence is a badge on the listing, so it belongs in the manifest;
      // the URLs themselves are small enough to come along.
      ...(team['p2w-video'] ? { 'p2w-video': team['p2w-video'] } : {}),
      ...(team['f2p-video'] ? { 'f2p-video': team['f2p-video'] } : {}),
      ...(team.videoUrl ? { videoUrl: team.videoUrl } : {}),
    });
  }
}

const dupes = teams.map((t) => t.id).filter((s, i, a) => a.indexOf(s) !== i);
if (dupes.length) throw new Error(`Teams: duplicate id(s) across groups: ${dupes.join(', ')}`);

// Best-first, matching the Team Builder's own `byRank` ordering so page one of
// the listing is correct without the client re-sorting.
teams.sort((a, b) => (a.rank ?? Number.MAX_SAFE_INTEGER) - (b.rank ?? Number.MAX_SAFE_INTEGER));

fs.writeFileSync(OUT_FILE, `${JSON.stringify({ note: NOTE, teams }, null, 2)}\n`);
console.log(
  `Teams: indexed ${teams.length} comp(s) across ${groups.length} group(s) → BSRData/Teams/Index.json`,
);
