/**
 * Compile the per-set stamp-set JSONs in BSRData/StampSets/*.json into the
 * single aggregate the web app bundles (Web/Source/Data/StampSets.json).
 *
 * Each stamp set is its OWN file under BSRData/StampSets/ (the source of truth,
 * deliberately NOT in BSRData/Data so it isn't synced with the scraped
 * character data). This script gathers them, sorts them so real sets lead and
 * placeholders trail, and writes the combined `{ note, sets: [...] }` shape the
 * app imports synchronously — the same relationship Data/ has with Public/Data.
 *
 * Run:  node BSRData/GenerateStampSets.mjs
 * Wired into Build.ps1 (step 2c) so the bundle stays in sync with the sources.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(here, 'StampSets');
const OUT_FILE = path.join(here, '..', 'Web', 'Source', 'Data', 'StampSets.json');

const NOTE =
  'GENERATED by BSRData/GenerateStampSets.mjs from BSRData/StampSets/*.json — edit the per-set ' +
  'files there, not this aggregate. Equipping all THREE rollable stamps (Stamp 1/2/3) of one set ' +
  'grants its 3-piece bonus. Most SSRs have a set; SR/SR+ have none, and Kaname Tosen (SSR) has ' +
  'none. Only Duty Borne carries real numbers; every set flagged "placeholder": true is a dummy. ' +
  '`effects` use the damage-tool target space (all | slash | strike | thrust | spirit | basic | ' +
  'technique | ultimate | special | counter | battlefield | ailment | shred). `stacks` is ' +
  'documentation only — the value shown is already the total at max stacks.';

const files = fs
  .readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort();

const sets = files.map((f) => {
  const set = JSON.parse(fs.readFileSync(path.join(SRC_DIR, f), 'utf8'));
  if (set.id !== path.basename(f, '.json')) {
    throw new Error(`StampSets: ${f} has id "${set.id}" — the filename must match the id.`);
  }
  return set;
});

// Real sets first, then placeholders; alphabetical within each group.
sets.sort((a, b) => Number(a.placeholder) - Number(b.placeholder) || a.name.localeCompare(b.name));

fs.writeFileSync(OUT_FILE, `${JSON.stringify({ note: NOTE, sets }, null, 2)}\n`);
console.log(`StampSets: compiled ${sets.length} sets → ${path.relative(path.join(here, '..'), OUT_FILE)}`);
