/**
 * Compile the per-banner JSONs under BSRData/Banners/<year>/<slug>.json into
 * the single manifest the web app fetches first (BSRData/Banners/Index.json).
 *
 * Layout — one file per banner, foldered by the YEAR the banner ran:
 *
 *   BSRData/Banners/2025/ichigo-bankai-unleashed.json   <- the full record
 *   BSRData/Banners/2026/gin-silver-flash.json
 *   BSRData/Banners/Leaks.json                          <- hand-maintained
 *   BSRData/Banners/Rumors.json                         <- hand-maintained
 *   BSRData/Banners/Index.json                          <- GENERATED (this file)
 *
 * Leaks and rumors are deliberately NOT split per record: they are a short,
 * churn-heavy list with no stable identity to name a file after, so they stay
 * whole and are folded into the manifest here.
 *
 * The manifest carries only the fields needed to CLASSIFY and LIST a banner
 * (name, featured slugs, date range). Everything else — `note`, `image`,
 * `source` — lives only in the per-banner file and is fetched on demand, which
 * is what lets /upcoming page the archive ten at a time instead of shipping the
 * whole history on first paint.
 *
 * Adding a banner: drop a new JSON in the right year folder and re-run. There
 * is no list to keep in sync by hand.
 *
 * Run:  node BSRData/GenerateBannerIndex.mjs
 * Wired into Build.ps1 (step 2e).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(here, 'Banners');
const OUT_FILE = path.join(DIR, 'Index.json');

/**
 * Every path segment the web app will interpolate into a fetch URL is
 * validated here, at build time, against the same character class the client
 * re-checks at runtime (see Web/Source/Lib/Data.ts `safeSegment`). Keeping the
 * two in lockstep means a hostile or fat-fingered filename can never widen into
 * a path-traversal or origin-escape on the client.
 */
const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const YEAR_RE = /^\d{4}$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

const NOTE =
  'GENERATED by BSRData/GenerateBannerIndex.mjs from BSRData/Banners/<year>/*.json plus ' +
  'Leaks.json and Rumors.json — edit those, never this file. Entries here are SUMMARIES; the ' +
  'full banner record (note/image/source) lives in the per-banner file at `path`.';

const years = fs
  .readdirSync(DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && YEAR_RE.test(d.name))
  .map((d) => d.name)
  .sort();

const banners = [];
for (const year of years) {
  const files = fs
    .readdirSync(path.join(DIR, year))
    .filter((f) => f.endsWith('.json'))
    .sort();

  for (const file of files) {
    const slug = path.basename(file, '.json');
    if (!SLUG_RE.test(slug)) {
      throw new Error(`Banners: "${year}/${file}" — filename must be kebab-case [a-z0-9-].`);
    }

    const rel = `${year}/${file}`;
    const banner = JSON.parse(fs.readFileSync(path.join(DIR, year, file), 'utf8'));

    if (banner.slug !== slug) {
      throw new Error(`Banners: ${rel} has slug "${banner.slug}" — it must match the filename.`);
    }
    if (String(banner.year) !== year) {
      throw new Error(`Banners: ${rel} has year "${banner.year}" — it must match the folder.`);
    }
    if (!banner.name || !banner.name.trim()) {
      throw new Error(`Banners: ${rel} has no name.`);
    }
    for (const key of ['startDate', 'endDate']) {
      if (banner[key] !== undefined && !DATE_RE.test(banner[key])) {
        throw new Error(`Banners: ${rel} has a malformed ${key} ("${banner[key]}") — want YYYY-MM-DD.`);
      }
    }
    // The folder is the year the banner RAN, so it has to agree with the dates.
    const dateYear = (banner.startDate || banner.endDate || '').slice(0, 4);
    if (dateYear && dateYear !== year) {
      throw new Error(`Banners: ${rel} sits in ${year}/ but its dates say ${dateYear}.`);
    }

    banners.push({
      slug,
      year: Number(year),
      path: rel,
      name: banner.name,
      slugs: banner.slugs ?? [],
      ...(banner.startDate ? { startDate: banner.startDate } : {}),
      ...(banner.endDate ? { endDate: banner.endDate } : {}),
    });
  }
}

const dupes = banners.map((b) => b.slug).filter((s, i, a) => a.indexOf(s) !== i);
if (dupes.length) throw new Error(`Banners: duplicate slug(s) across years: ${dupes.join(', ')}`);

const readList = (file) => {
  const p = path.join(DIR, file);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : [];
};

// Newest first — the same order /upcoming pages through the archive in, so the
// client never has to re-sort the whole manifest before showing page one.
banners.sort((a, b) => (b.startDate ?? '').localeCompare(a.startDate ?? ''));

const index = { note: NOTE, banners, leaks: readList('Leaks.json'), rumors: readList('Rumors.json') };
fs.writeFileSync(OUT_FILE, `${JSON.stringify(index, null, 2)}\n`);
console.log(
  `Banners: indexed ${banners.length} banner(s) across ${years.length} year(s), ` +
    `${index.leaks.length} leak(s), ${index.rumors.length} rumor(s) → BSRData/Banners/Index.json`,
);
