/**
 * Where per-character JSON lives, for the Node-side tooling.
 *
 * The Go pipeline has the same knowledge in BSRData/internal/charstore; this is
 * the JavaScript half. Keep the two in step — between them they are the only
 * places that should know the on-disk layout:
 *
 *   BSRData/Characters/2025/ichigo-bankai.json
 *   BSRData/Characters/2026/ichigo-ts.json
 *   BSRData/Characters/Index.json            <- generated by BSRData/Curate
 *
 * The year folder is an organisational bucket, never part of a character's
 * identity: a character is addressed by SLUG, and `find` resolves the slug to
 * whichever year holds it. Scripts must not join a character path by hand — if
 * a release date is corrected and a file moves years, only this file should
 * need to know.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** BSRData root, derived from this file's own location. */
export const BSR_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

/** The character folder. */
export const CHARACTERS_DIR = path.join(BSR_ROOT, 'Characters');

/** The generated manifest inside it. */
export const INDEX_FILE = path.join(CHARACTERS_DIR, 'Index.json');

/** Mirrors `charstore.ValidSlug` and Web/Source/Lib/Data.ts `safeSegment`. */
const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Year folders, oldest first. "unknown" is a deliberate escape hatch for a
 * character whose release date hasn't been filled in yet — it is walked like
 * any other bucket so such a character is never invisible to the tooling.
 */
function yearDirs(root = CHARACTERS_DIR) {
  if (!fs.existsSync(root)) return [];
  return fs
    .readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && (/^\d{4}$/.test(d.name) || d.name === 'unknown'))
    .map((d) => d.name)
    .sort();
}

/**
 * Every character file as `{ slug, year, file, rel }`, sorted by slug so
 * downstream output is stable regardless of directory-read order.
 *
 * `file` is an absolute path; `rel` is relative to the Characters folder
 * ("2026/ichigo-ts.json") — the same string the web app's index carries.
 */
export function listCharacterFiles(root = CHARACTERS_DIR) {
  const out = [];
  for (const year of yearDirs(root)) {
    for (const name of fs.readdirSync(path.join(root, year)).sort()) {
      if (!name.endsWith('.json')) continue;
      const slug = path.basename(name, '.json');
      if (!SLUG_RE.test(slug)) {
        throw new Error(`Characters: ${year}/${name} — filename must be kebab-case [a-z0-9-].`);
      }
      out.push({ slug, year, file: path.join(root, year, name), rel: `${year}/${name}` });
    }
  }
  return out.sort((a, b) => a.slug.localeCompare(b.slug));
}

/** Resolve a slug to its file, or null when the character has none yet. */
export function findCharacterFile(slug, root = CHARACTERS_DIR) {
  if (!SLUG_RE.test(slug)) throw new Error(`Characters: unsafe slug "${slug}".`);
  for (const year of yearDirs(root)) {
    const p = path.join(root, year, `${slug}.json`);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/** Parse every character file. Yields `{ slug, year, file, rel, char }`. */
export function readCharacters(root = CHARACTERS_DIR) {
  return listCharacterFiles(root).map((entry) => ({
    ...entry,
    char: JSON.parse(fs.readFileSync(entry.file, 'utf8')),
  }));
}

/** Read one character by slug. Throws if it has no file. */
export function readCharacter(slug, root = CHARACTERS_DIR) {
  const file = findCharacterFile(slug, root);
  if (!file) throw new Error(`Characters: no JSON for slug "${slug}".`);
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/** Write a character back to the file it came from, preserving 2-space JSON. */
export function writeCharacter(file, char) {
  fs.writeFileSync(file, `${JSON.stringify(char, null, 2)}\n`, 'utf8');
}
