// Regenerates Characters/Index.json for the site. Run with:
//
//	cd BSRData/Curate && go run .
//
// NOTE: this program does not merge any curated fields into the per-character
// JSON files — those are owned solely by the scraper (which only creates JSON
// for NEW characters). Curate is limited to rebuilding the character index from
// whatever per-character JSON already exists under Characters/<year>/.
//
// It writes exactly one file, Characters/Index.json. Everything else in BSRData
// is either hand-maintained or generated by a sibling script:
//
//	Characters/<year>/<slug>.json  scraper-owned (new characters) + hand-edited
//	Banners/<year>/<slug>.json     hand-maintained; indexed by GenerateBannerIndex.mjs
//	Banners/Leaks.json, Rumors.json  hand-maintained, folded into the banner index
//	Teams/<group>/<id>.json        hand-maintained; indexed by GenerateTeamIndex.mjs
//	Data/Glossary.json             hand-maintained, keyed per character slug
//
// Whether a banner is shown as live, upcoming, or archived is computed by the
// site purely from its startDate/endDate vs. today — see classifyBanners in
// Web/Source/Lib/Banner.ts. Nothing here sets a status flag.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"bsrdata/internal/charstore"
)

func main() {
	root, err := findRoot()
	if err != nil {
		panic(err)
	}
	fmt.Println("BSRData root:", root)
	fmt.Println("Characters:  ", charstore.Dir(root))

	n, err := charstore.WriteIndex(root, func(msg string) {
		fmt.Println("  !", msg)
	})
	if err != nil {
		fmt.Printf("  ! index regen: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  + Characters/Index.json regenerated (%d characters)\n", n)
}

// findRoot locates the BSRData root whether this is run from BSRData/Curate
// (the documented way) or from BSRData itself.
func findRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for _, candidate := range []string{filepath.Join(wd, ".."), wd} {
		if _, err := os.Stat(charstore.Dir(candidate)); err == nil {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("could not find a %s dir from %s", charstore.DirName, wd)
}
